(function(){
  'use strict';
  const LS_DOWNLOADS='qf_offline_downloads';
  const LS_DISMISSED='qf_update_dismissed_build';
  const APK_UA=/; wv\)|Android.*Version\/\d+|QasimFlixAPK/i.test(navigator.userAgent);
  const standalone=window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone;
  const mobile=window.matchMedia('(max-width: 768px)').matches || /Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
  if (mobile || standalone || APK_UA) document.documentElement.classList.add('qf-mobile-root'), document.body && document.body.classList.add('qf-apk-mode');
  function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();}
  function toast(msg){let el=document.querySelector('.qf-apk-toast');if(!el){el=document.createElement('div');el.className='qf-apk-toast';document.body.appendChild(el);}el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600);} window.qfToast=toast;
  function getDownloads(){try{return JSON.parse(localStorage.getItem(LS_DOWNLOADS)||'[]')}catch(e){return[]}}
  function saveDownloads(items){localStorage.setItem(LS_DOWNLOADS,JSON.stringify(items.slice(0,80)));}
  function registerDownload(item){const items=getDownloads().filter(x=>x.url!==item.url);items.unshift({title:item.title||'Video',url:item.url,type:item.type||'video',createdAt:Date.now()});saveDownloads(items);}
  window.qfRegisterDownload=registerDownload;
  function canDirectDownload(url){return !!url && /\.mp4(\?|#|$)/i.test(url) && !/(drive\.google|youtube|youtu\.be|iframe|embed)/i.test(url);}
  window.qfCanDirectDownload=canDirectDownload;
  function openSearch(){const input=document.getElementById('search-input'); if(input){input.focus(); input.scrollIntoView({block:'center',behavior:'smooth'});}}
  function renderDownloads(){const sheet=document.getElementById('qf-downloads-sheet'); if(!sheet)return; const items=getDownloads(); const list=sheet.querySelector('[data-qf-download-list]'); if(!items.length){list.innerHTML='<div class="qf-empty-downloads">Henüz indirme yok.<br>MP4 destekli içeriklerde “İndir” butonuna basınca burada görünür.</div>';return;} list.innerHTML=items.map(x=>`<div class="qf-download-card"><div><b>${escapeHtml(x.title)}</b><small>${new Date(x.createdAt).toLocaleString('tr-TR')}</small></div><a href="${escapeAttr(x.url)}" target="_blank" rel="noopener">Aç</a></div>`).join('');}
  function openDownloads(){renderDownloads();document.getElementById('qf-downloads-sheet')?.classList.add('open');setActive('downloads');}
  function closeDownloads(){document.getElementById('qf-downloads-sheet')?.classList.remove('open');}
  window.qfOpenDownloads=openDownloads; window.qfCloseDownloads=closeDownloads;
  function setActive(name){document.querySelectorAll('.qf-mobile-bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.qfTab===name));}
  function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
  function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;');}
  function injectUI(){if(document.getElementById('qf-mobile-bottom-nav'))return; const nav=document.createElement('nav'); nav.id='qf-mobile-bottom-nav'; nav.className='qf-mobile-bottom-nav'; nav.setAttribute('aria-label','APK alt menü'); nav.innerHTML=`
    <button class="active" data-qf-tab="home" type="button"><span>⌂</span><small>Ana Sayfa</small></button>
    <button data-qf-tab="search" type="button"><span>⌕</span><small>Arama</small></button>
    <button data-qf-tab="downloads" type="button"><span>⇩</span><small>İndirilenler</small></button>
    <button data-qf-tab="favorites" type="button"><span>♡</span><small>Favoriler</small></button>
    <button data-qf-tab="profile" type="button"><span>◉</span><small>Profil</small></button>`; document.body.appendChild(nav);
    nav.addEventListener('click',e=>{const btn=e.target.closest('button'); if(!btn)return; const tab=btn.dataset.qfTab; setActive(tab); if(tab==='home'){closeDownloads(); if(window.showAll) window.showAll(); window.scrollTo({top:0,behavior:'smooth'});} if(tab==='search'){closeDownloads(); openSearch();} if(tab==='downloads') openDownloads(); if(tab==='favorites'){closeDownloads(); window.loadFavorites?window.loadFavorites():toast('Favoriler için giriş yapmalısın.');} if(tab==='profile'){closeDownloads(); if(window.openProfileSelectScreen) window.openProfileSelectScreen(); else document.getElementById('local-auth-btn')?.click();}});
    const sheet=document.createElement('section'); sheet.id='qf-downloads-sheet'; sheet.className='qf-downloads-sheet'; sheet.innerHTML='<div class="qf-downloads-head"><h3>İndirilenler</h3><button class="qf-sheet-close" onclick="qfCloseDownloads()">×</button></div><div data-qf-download-list></div>'; document.body.appendChild(sheet);
    const banner=document.createElement('div'); banner.id='qf-update-banner'; banner.className='qf-update-banner'; banner.innerHTML='<div style="flex:1"><strong>Yeni APK sürümü var</strong><p data-qf-update-msg>Uygulamayı güncellemen önerilir.</p></div><a data-qf-update-link href="#" target="_blank" rel="noopener">Güncelle</a><button type="button" data-qf-update-close>Sonra</button>'; document.body.appendChild(banner); banner.querySelector('[data-qf-update-close]').onclick=()=>{localStorage.setItem(LS_DISMISSED,banner.dataset.build||'');banner.classList.remove('show')};
  }
  async function checkUpdate(){try{const res=await fetch('/version.json?ts='+Date.now(),{cache:'no-store'}); if(!res.ok)return; const data=await res.json(); if(!data.apkRequired && !data.apkUrl)return; const dismissed=localStorage.getItem(LS_DISMISSED); const build=String(data.build||data.version||''); if(dismissed===build)return; const b=document.getElementById('qf-update-banner'); if(!b)return; b.dataset.build=build; b.querySelector('[data-qf-update-msg]').textContent=data.message||'Yeni sürüm mevcut.'; const a=b.querySelector('[data-qf-update-link]'); if(data.apkUrl){a.href=data.apkUrl; a.style.display='inline-block';} else {a.style.display='none';} b.classList.add('show');}catch(e){}}
  function enhanceInstallTip(){let deferredPrompt=null; window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e; if(localStorage.getItem('qf_install_tip_closed'))return; const tip=document.createElement('div'); tip.className='qf-install-tip show'; tip.innerHTML='<button>Kapat</button>QasimFlix’i telefona uygulama gibi ekleyebilirsin.'; document.body.appendChild(tip); tip.onclick=async(ev)=>{if(ev.target.tagName==='BUTTON'){localStorage.setItem('qf_install_tip_closed','1');tip.remove();return;} if(deferredPrompt){deferredPrompt.prompt(); await deferredPrompt.userChoice; tip.remove();}};});}
  function keepScreenAwake(){document.addEventListener('click',async e=>{if(!e.target.closest('.btn-play,.card,.ep-card,#fullscreen-btn,.landscape-start'))return; try{if('wakeLock' in navigator && !window.qfWakeLock){window.qfWakeLock=await navigator.wakeLock.request('screen'); window.qfWakeLock.addEventListener('release',()=>window.qfWakeLock=null);}}catch(_){}}); document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible') window.qfWakeLock=null;});}
  function overrideDownload(){const original=window.downloadItem; window.downloadItem=function(type,itemId,videoUrl,title){ if(!videoUrl && window.currentSeries?.seasons?.[0]?.episodes?.[0]) videoUrl=window.currentSeries.seasons[0].episodes[0].videoUrl; if(!canDirectDownload(videoUrl)){toast('Bu video çevrimdışı indirme için uygun değil. Sadece direkt MP4 desteklenir.'); return;} registerDownload({title:title||'Video',url:videoUrl,type}); if(original) return original.apply(this,arguments); const a=document.createElement('a'); a.href=videoUrl; a.download=(title||'video')+'.mp4'; a.target='_blank'; document.body.appendChild(a); a.click(); a.remove(); toast('İndirme başlatıldı.'); };
  }
  ready(()=>{document.body.classList.add('qf-apk-mode'); injectUI(); checkUpdate(); enhanceInstallTip(); keepScreenAwake(); setTimeout(overrideDownload,300); const action=new URLSearchParams(location.search).get('action'); if(action==='downloads') setTimeout(openDownloads,350); if(action==='search') setTimeout(openSearch,350); window.addEventListener('online',()=>toast('Bağlantı geri geldi.')); window.addEventListener('offline',()=>toast('İnternet yok. Çevrimdışı mod.'));});
})();
